"""добалены колонки с количеством книг

Revision ID: 40bde73a24f3
Revises: 
Create Date: 2022-04-10 13:34:24.369590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40bde73a24f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('total_amount', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('amount_in_library', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'amount_in_library')
    op.drop_column('books', 'total_amount')
    # ### end Alembic commands ###
