"""добавлена таблица types_marks

Revision ID: 4f6edb981b25
Revises: 
Create Date: 2022-04-24 16:20:09.449070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6edb981b25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_marks', 'book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_marks', sa.Column('book', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
