"""добавлена колонка с ссылкой на маленькую картинку (таблица книги)

Revision ID: 5666fe2e2ce9
Revises: 
Create Date: 2022-04-11 17:03:31.026144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5666fe2e2ce9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('small_image_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'small_image_link')
    # ### end Alembic commands ###
