"""удалена ассоциация между комментариями и книгами

Revision ID: 56f5b4609b79
Revises: 4a500ad3a680
Create Date: 2022-04-24 16:25:25.480777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f5b4609b79'
down_revision = '4a500ad3a680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_comments',
    sa.Column('books', sa.INTEGER(), nullable=True),
    sa.Column('comments', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['books'], ['books.id'], ),
    sa.ForeignKeyConstraint(['comments'], ['comments.id'], )
    )
    # ### end Alembic commands ###
