"""в бд почему-то нет колонки с фото, может так она добавится

Revision ID: e80a468a9e74
Revises: 737c52af1e71
Create Date: 2022-04-19 22:14:44.817524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e80a468a9e74'
down_revision = '737c52af1e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo_link')
    # ### end Alembic commands ###
